/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SpelerSetting.java
 *
 * Created on 6-mei-2010, 20:30:45
 */
package gui.grafisch;

import domein.Domeincontroller;
import domein.Pion;
import domein.Speler;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JColorChooser;

/**
 *
 * @author Admin
 */
public class SpelerSetting extends javax.swing.JDialog {

    /** Creates new form SpelerSetting */
    int aantalSpelers;
    List<Speler> spelers = new ArrayList<Speler>();
    List<Pion> pionen;
    List<Pion> selectedPionen = new ArrayList<Pion>();
    java.awt.Frame parentFrame;
    String kleur;
    Domeincontroller domeinC;

    public List<Speler> getSpelers() {
        return spelers;
    }

    public int getAantalSpelers() {
        return aantalSpelers;
    }

    public void setAantalSpelers(int aantalSpelers) {
        this.aantalSpelers = aantalSpelers;
    }

    public SpelerSetting(java.awt.Frame parent, boolean modal, Domeincontroller dc) {
        super(parent, modal);
        initComponents();
        domeinC = dc;
        parentFrame = parent;
        jTextFieldName.setText("Speler 1");
        pionen = dc.getPionen();
        fillComboBox();

    }

    private void fillComboBox() {
        jComboBox1.removeAllItems();
        for (Pion pion : pionen) {
            if (selectedPionen.contains(pion)) {
                continue;
            }
            jComboBox1.addItem(pion.getKleurString());
        }
    }

    private void getSpeler() {
        String spelerName = jTextFieldName.getText();
        kleur = jComboBox1.getSelectedItem().toString();

        Pion selectedPion = getPionFromString(kleur);
        selectedPionen.add(selectedPion);
        spelers.add(new Speler(spelers.size(), spelerName, selectedPion, 10));
        if (spelers.size() < aantalSpelers) {
            jTextFieldName.setText("Speler " + (spelers.size() + 1));
            fillComboBox();
        } else {
            this.setVisible(false);
        }
    }

    private Pion getPionFromString(String s) {
        for (Pion pion : pionen) {
            if (pion.getKleurString() == s) {
                return pion;
            }
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonNext = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Speler");

        jLabel1.setText("Speler naam:");

        jLabel2.setText("Pion kleur:");

        jButtonNext.setText("Next player");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButtonNext)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        getSpeler();


    }//GEN-LAST:event_jButtonNextActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
